### ISSUE TITLE
Problem with certificate on Internet Explorer

### ISSUE THREAD

**Issue by tszkutnik** [enovation/moodle-atto_teamsmeeting#12]
Hi,

I have problem creating a meeting on Internet Explorer. After I navigate through ATTO to create teams meeting modal I get information:

Content was blocked because it was not signed by a valid security certificate.
For more information, see About Certificate Errors in Internet Explorer Help.

![IE](https://user-images.githubusercontent.com/44473920/84033758-aa459a00-a999-11ea-918a-beb7a306a0f2.png)

I have checked it on three different machines which only one of them showed the error (other had white screen, probably some settings somewhere?)

![Certificate](https://user-images.githubusercontent.com/44473920/84033761-ac0f5d80-a999-11ea-9fe3-66510b9e1a71.png)

Issue was spotted on Moodle 3.7 & 3.8.
IE version: 11.836.18362.0 & 11.1304.17134.0

**Comment by nenorojas** [comment]
Hi,

Plugin is not support for Internet Explorer 11 and Microsoft Teams compatibility to Internet Explorer 11 is also limited and will be dropped soon. https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams

Regards
