### ISSUE TITLE
Meeting link fails to populate input text

### ISSUE THREAD

**Issue by jairoserrano** [enovation/moodle-atto_teamsmeeting#16]
I have a problem with the plugin. When i try to create a meeting, the automatic link is not loading in the text input and it is necessary to manually copy the link and then paste it in the document.

I appreciate the collaboration you will would give me on this error:

![86145644-cb8f3700-babc-11ea-9642-9f3a6a35d6eb](https://user-images.githubusercontent.com/285757/86177346-14aaaf80-baec-11ea-8eba-d1427ce898b0.png)

**Comment by avegys** [comment]
Hi Jairo,

Could you double check what  Meetings App URL is set in your Teams Meeting Settings? 
You can find this setting by going to Site administration -> Plugins -> Text editors -> Atto HTML editor -> Teams Meeting Settings.

Best regards,
Andrius

**Comment by jairoserrano** [comment]
Hello!

i got: https://enovation.ie/msteams/#/signin

**Comment by avegys** [comment]
Hi Jairo,

Please change it to be just https://enovation.ie/msteams and your issue should be gone.

Best regards,
Andrius

**Comment by jairoserrano** [comment]
Great! that's all!

Thanks!
