### ISSUE TITLE
Attendance after scheduling meeting from Moodle gets blank

### ISSUE THREAD

**Issue by babaaldar** [enovation/moodle-atto_teamsmeeting#19]
We have installed plugin and started using it. We created the event in Moodle calendar and repeated same meeting in Moodle Calendar. When we took first meeting, we were able to download the attendance and also got all the record of students but when we have taken second meeting next week, we got the blank attendance even tried three - four times in between of that meeting still we get the blank attendance. Is that problem of same link repeated in the moodle calender? Is the recurrence meeting option available? or what else

**Comment by nenorojas** [comment]
Hi @babaaldar 

This plugin doesn't allow recurrent meetings, it's a simplified version of meeting created via Microsoft Teams app. You need to create one Moodle calendar entry for each meeting and one Atto Teams meeting for each. 

Regards
