### ISSUE TITLE
3.9 Compatibility

### ISSUE THREAD

**Issue by kinnectus** [enovation/moodle-atto_teamsmeeting#20]
Does this plugin have official compatibility for Moodle 3.9?

we can see on the Moodle plugin catalogue that it supports up to 3.8, but we wondered whether 3.9 is under review, or whether it is officially supported and hasn't had the Moodle catalogue updated.

Thank you.

**Comment by nenorojas** [comment]
Hi @kinnectus 

It's officially compatible to 3.9.

Any issues, please report an issue to be addressed.

Regards
