### ISSUE TITLE
Meeting is not being created

### ISSUE THREAD

**Issue by vitordio** [enovation/moodle-atto_teamsmeeting#21]
Hi,

I installed the plugin and configured it according to documentation. I created a Microsoft account and enabled Teams correctly.

However, in Moodle, after entering the meeting name and date information, the message that the meeting was not successfully created.

Inspecting, I can see the messages being returned but I can't understand why, could they help me? The app is still in: https://enovation.ie/msteams

![image](https://user-images.githubusercontent.com/56653783/90397492-5082df80-e06e-11ea-9a44-6a270d683b28.png)
![image](https://user-images.githubusercontent.com/56653783/90397524-5bd60b00-e06e-11ea-9789-e019300e47c4.png)
![image](https://user-images.githubusercontent.com/56653783/90397680-98096b80-e06e-11ea-96bc-fd92d46ba76a.png)

**Comment by abdallah84** [comment]
We have same issue

**Comment by vitordio** [comment]
> We have same issue

Hi Abdallah,
Did you figure it out?

**Comment by abdallah84** [comment]
no still not solved :(

**Comment by vitordio** [comment]
> no still not solved :(

:/

**Comment by nenorojas** [comment]
Hi @vitordio, @abdallah84,

You need to be sure that you are using an Office 365 with Microsoft Teams license and that your administrator granted permissions to use the shared application https://enovation.ie/msteams. You also need to be sure there's no firewall issues between Moodle and this application. 

If the above it's not possible, you can host your own meetings app: 
https://github.com/enovation/moodle-atto_teamsmeeting/blob/master/README.md

Regards
