### ISSUE TITLE
Link displayed

### ISSUE THREAD

**Issue by tuttyk** [enovation/moodle-atto_teamsmeeting#23]
Hello,

The plugin works for me (Moodle 3.8) but the displayed link is to long.  What can I do to show only  "TEAMS MEETING"  ?
Why the meeting created is not visible in the calendar of the application (TEAMS) ?

![teams](https://user-images.githubusercontent.com/69959796/94938201-cb923f00-04d0-11eb-893c-d99f3b404069.PNG)

Thanks for your attention in this issue.

**Comment by nenorojas** [comment]
Hi @tuttyk ,

Thanks for the suggestion, it's related to #13 where the suggestion is instead of bringing the URL, to add a link using the meeting title, so I'm closing as a duplicate.

Regards
