### ISSUE TITLE
"atto_teamsmeeting" table does not exist

### ISSUE THREAD

**Issue by jojolangelot** [enovation/moodle-atto_teamsmeeting#25]
I can connect to Microsoft Teams, but when I choose to create a meeting, I get amessage that says ""atto_teammeeting" does not exist. 

Any idea ?

**Comment by nenorojas** [comment]
Hi @jojolangelot ,

We need more details, please provide your Moodle version and screenshot of the error.
I'd recommend you to try to uninstall and install the plugin again. 

Regards

**Comment by jojolangelot** [comment]
Moodle is 3.9.2, here is the screenshot.

**Comment by weilai-irl** [comment]
Hi @jojolangelot,

The screenshot wasn't added correctly from email attachment, unfortunately. Could you try adding them again from github please.

Also, based on the title of the issue, it looks like the "atto_teamsmeeting" database table, which should be created when installing the plugin, doesn't exist in your database. Could you do the following check please:
 - Go to the **Plugins overview** page of your Moodle site, and confirm **Teams Meeting** plugin is installed on your site.
 - Go to the database of your Moodle site, and confirm if a table named **mdl_atto_teamsmeeting** exists (assuming your tables are prefixed with mdl_).

If your answer to the questions are "yes" and "no", then try to uninstall the plugin from the **Plugins overview** page, and reinstall it again, to see if the table gets created in the database.

Regards,
Lai

**Comment by jojolangelot** [comment]
Thanks for your reply. It got resolved by uninstalling and reinstalling the
plugin, apparently it had not created the table.
Best regards.

**Comment by weilai-irl** [comment]
@jojolangelot Thank you for your confirmation.
