### ISSUE TITLE
Full moodle plugin support

### ISSUE THREAD

**Issue by pachainti** [enovation/moodle-atto_teamsmeeting#26]
Hi,
the plugin is good and works well. However, in my opinion it would be good to have a plugin that allow to add an activity or a resource as those of [BBB](https://moodle.org/plugins/mod_bigbluebuttonbn) and [jitsi](https://moodle.org/plugins/mod_jitsi).

**Comment by nenorojas** [comment]
Hi @pachainti ,

That's is not something in the plans for the future, but there's a plugin (not developed or supported) by Enovation that you could try:

https://moodle.org/plugins/mod_msteams

Regards
