### ISSUE TITLE
Why teams link is awful ?

### ISSUE THREAD

**Issue by markham89** [enovation/moodle-atto_teamsmeeting#27]
Hi,
When i generate a teams link i have an awful long teams link instead short text 

expectation : 

[Join Teams (or title of meeting or beautiful icon)](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjBfffjMGxxQwNTUtMzFhMxxxS00NTg4LWJhZTItNfsgThhYmM4NjdiNDFk%40thread.v2/0?context=%7b%22Tid%22%xxxxxxxxx-x-x-x-x-xxxxxxxxx-x-x-xxxxxx-x-x--x-x-x-x-x-x---x-x-x-x-x-xxd)

my link : 
[https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjBfffjMGxxQwNTUtMzFhMxxxS00NTg4LWJhZTItNfsgThhYmM4NjdiNDFk%40thread.v2/0?context=%7b%22Tid%22%xxxxxxxxx-x-x-x-x-xxxxxxxxx-x-x-xxxxxx-x-x--x-x-x-x-x-x---x-x-x-x-x-xxd](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjBfffjMGxxQwNTUtMzFhMxxxS00NTg4LWJhZTItNfsgThhYmM4NjdiNDFk%40thread.v2/0?context=%7b%22Tid%22%xxxxxxxxx-x-x-x-x-xxxxxxxxx-x-x-xxxxxx-x-x--x-x-x-x-x-x---x-x-x-x-x-xxd)

Moodle 3.9.2

**Comment by avegys** [comment]
Hi markham89,

This feature works like standard link feature. You can type any text you want for the link. Then select it and click teams meeting button to create meeting link for the text that you typed.

Best regards,
Andrius
