### ISSUE TITLE
Privacy API

### ISSUE THREAD

**Issue by rschrenk** [enovation/moodle-atto_teamsmeeting#28]
Hello,

I used your plugin as inspiration to create a moodle module. @mudrd8mz made me aware of the fact that the plugin shares the users language with the MS Teams App and this should be revealed using the privacy API (https://github.com/center-for-learning-management/moodle-mod_msteams/issues/11).

I already implemented this in my plugin, so perhaps you can also use this piece of code to improve your use of privacy API.

https://github.com/center-for-learning-management/moodle-mod_msteams/blob/master/classes/privacy/provider.php

Kind regards

**Comment by mudrd8mz** [comment]
Thank you @rschrenk  for sharing!

**Comment by avegys** [comment]
@rschrenk 

Thank you for your input! The privacy API has been updated.
