### ISSUE TITLE
Can't create Teams-Meeting - License Issuu?

### ISSUE THREAD

**Issue by RS-HWZ** [enovation/moodle-atto_teamsmeeting#29]
Hi folks
when we want to Create a Teams-Meeting we get an Error at point 3. in the Usage Guide after clicking Create (see Pic, Error means: closed the connection unexpectedly.)
![teams_atto_A5lizenz_problem](https://user-images.githubusercontent.com/78536914/107045514-deda5180-67c5-11eb-9b5f-2149382b5cf8.png)

this Problem just happens on User they have a Office 365 Education A5 License, Users with a Education A1 License dosn't have the problem.

**Comment by nenorojas** [comment]
Hi @RS-HWZ 

This doesn't look like a permission issue but an issue to display the iframe.

Can you please try to go straight to https://enovation.ie/msteams/ and try to create a meeting there?

Regards

**Comment by stereo-cmd** [comment]
We seem to have the same/similar problem. 
Creating a meeting without moodle (using: https://enovation.ie/msteams/) triggers the same error as within moodle (using atto editor/moodle-atto_teamsmeeting): 

"Oops! Your meeting wasn't created successfully.
Please try again. If the problem persists, check with your IT administrator to ensure you have the proper permissions."

"Hoppla! Ihre Besprechung wurde nicht erfolgreich erstellt.
Bitte versuchen Sie es erneut. Wenn das Problem weiterhin besteht, fragen Sie bei Ihrem IT-Administrator nach, um sicherzustellen, dass Sie über die entsprechenden Berechtigungen verfügen."

Does anyone have an idea which permission could provoke this error? 
It does not seem to be an iframe/display issue as far as I see.
We have different user with different microsoft licenses and the error only occurs for users with a certain license type.

Thanks for your help!

**Comment by nenorojas** [comment]
HI @RS-HWZ ,

Please try to check your server configurations, the issue might be related to this case: https://github.com/enovation/moodle-atto_teamsmeeting/issues/43

Regards
