### ISSUE TITLE
teams.microsoft.com refused to connect

### ISSUE THREAD

**Issue by akoharek** [enovation/moodle-atto_teamsmeeting#30]
we have installed the plugin but when we want to create the meeting in the pop up we got an error message: teams.microsoft.com refused to connect. We have office365 business standard subscription, I'm logged in to Moodle using openid with my office365 user.

**Comment by akoharek** [comment]
hi there! can you confirm that you've seen this issue?

**Comment by nenorojas** [comment]
Hi @akoharek 

Can you please try to go directly to https://enovation.ie/msteams and create a meeting? It might be an issue displaying the iframe within your Moodle. Please send us some screenshots of the issue to check. 

Regards

**Comment by akoharek** [comment]
HI @nenorojas !

it is working using your address. Please see the error screen when using https://teams.microsoft.com 

thanks

<img width="487" alt="atto teams error" src="https://user-images.githubusercontent.com/12859908/116369572-d2382900-a809-11eb-950c-7f4cc03a39b1.png">

**Comment by nenorojas** [comment]
Hi @akoharek ,

If you can access the site it means that something in your Moodle environment/hosting is blocking the iframe with the application https://enovation.ie/msteams from loading when you try to access it via your Moodle site. 

I'd recommend to ask you hosting provider to check the logs and try to find out the reason.

Regards

**Comment by nikita-rane-22** [comment]
Hi @nenorojas,

I am facing the same issue, just wondering if you can provide a fix for this.

Regards

**Comment by nenorojas** [comment]
Hi, @nikita-rane-22 @akoharek ,

As mentioned in the documentation, you need to use under /admin/settings.php?section=atto_teamsmeeting_settings the address https://enovation.ie/msteams if you don't have another instance of meeting app hosted in another location. 

![image](https://user-images.githubusercontent.com/3680797/122363806-25e50a00-cf51-11eb-859e-94de5a710610.png)

https://teams.microsoft.com is not a valid address to use. 

Regards
