### ISSUE TITLE
 Is it possible to limit the calendar

### ISSUE THREAD

**Issue by neeesn** [enovation/moodle-atto_teamsmeeting#31]
Hi,

Is it possible to limit the calendar, so the end date cant be more then 60 days apart from the start date, since the duration can only be 60 days? ( https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams ) - Some teachers think they can have an open meeting they can join, running for a whole school year. - So they use the same meeting instance every morning

**Comment by nenorojas** [comment]
Hi @neeesn ,

I'm afraid that's something outside of the plugin control. On the MIcrosoft documentation it says:


Regards
