### ISSUE TITLE
time out issue

### ISSUE THREAD

**Issue by fweissman** [enovation/moodle-atto_teamsmeeting#32]
When creating a meeting a time out occurs linking to enovation.ie … start issue april 24th

**Comment by nenorojas** [comment]
Hi @fweissman ,

Is the issue still happening or was it a temporary issue? Please note that https://enovation.ie/msteams is a shared application provided via Enovation hosting, you can also create and host your own application https://github.com/enovation/moodle-atto_teamsmeeting.

Regards

**Comment by babaaldar** [comment]
Same issue.
It ask login for Moodle again in the same window.

**Comment by nenorojas** [comment]
Hi @babaaldar,

Please provide some screenshots of what you see when you try to access https://enovation.ie/msteams, please be sure that there's no firewall issues to access this page.

Regards

**Comment by fweissman** [comment]
It was just one day, butnwe will keep an eye out so maybe change to own hosting

**Comment by babaaldar** [comment]
> Hi @babaaldar,
> 
> Please provide some screenshots of what you see when you try to access https://enovation.ie/msteams, please be sure that there's no firewall issues to access this page.
> 
> Regards

![Screenshot (4)](https://user-images.githubusercontent.com/36961656/116508115-4a701e80-a8de-11eb-8ad4-2130dee311ea.png)

**Comment by nenorojas** [comment]
HI @babaaldar ,

You screenshot suggests that the URL on this page /admin/settings.php?section=atto_teamsmeeting_settings is not pointing to https://enovation.ie/msteams but to your Moodle site. Please use the default URL or a proper custom app URL.

Regards

**Comment by babaaldar** [comment]
Hi,
I have given same URL https://enovation.ie/msteams 
![image](https://user-images.githubusercontent.com/36961656/116782436-c4530400-aaa6-11eb-82e7-4b89ccb4d305.png)
![image](https://user-images.githubusercontent.com/36961656/116782451-e482c300-aaa6-11eb-9dcc-bae708fab641.png)
then When I click on Create, after few second , 
I am getting below page 
![image](https://user-images.githubusercontent.com/36961656/116782497-15fb8e80-aaa7-11eb-8a58-d3608fb0f9ce.png)
It is expected the Link should get return but see..
It happens from last 4 days, earlier it was fine.

Regards
Babaso Aldar
