### ISSUE TITLE
Strange Problem when create Teams Meeting in Moodle

### ISSUE THREAD

**Issue by Guzo88** [enovation/moodle-atto_teamsmeeting#33]
We have been using the Teams plugin for half a year.  So far, everything has worked fine. However, a week ago an interesting phenomenon began. Some users reported, when they want create Meeting, and setting up the time and name, then click Create button, the meeting isn't created. Normally, the Set Up Meeting and Open Meeting button should appear, along with a link. Instead, they see the Moodle login interface again in the small window. This phenomenon does not occur in all users, usually those who have saved their user names and passwords, and use Google Chrome. We tried clearing passwords, clearing browsing history, clearing Moodle cache, reinstalling the browser, reinstalling Teams plugin, nothing used. However, if they log in via another browser, they can create the link, but the browser used until then does not want to work at all. Any ideas?

**Comment by Guzo88** [comment]
I found the problem. Google Chrome latest version causes the problem.

**Comment by mandeepmaurya79** [comment]
Any solution for this problem?

**Comment by nenorojas** [comment]
@Guzo88 @mandeepmaurya79  We couldn't reproduce the issue with latest version of Chrome https://github.com/enovation/moodle-atto_teamsmeeting/issues/34. If you provide step by step details so we can reproduce we can investigate for a solution.

**Comment by rafaelacolooli** [comment]
Any solution for this problem?
