### ISSUE TITLE
IE11 - Object doesn't support this action

### ISSUE THREAD

**Issue by christopher-learningpool** [enovation/moodle-atto_teamsmeeting#36]
Unable to load https://enovation.ie/msteams within the atto editor iframe when using the IE11 browser and pre-chromium Edge browsers.

Console log: Object doesn't support this action

Line breaks on: translate.ts:41 
`let paramlocale = url.searchParams.get('locale');`

URL.searchParams() isn't supported in IE11.

Can you confirm if IE11 is supported?

**Comment by nenorojas** [comment]
Hi @christopher-learningpool 

We are not fixing issues anymore on IE11, only latest versions of Edge. 

https://docs.microsoft.com/en-us/microsoftteams/unsupported-browsers

Regards
