### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by mirstigais** [enovation/moodle-atto_teamsmeeting#37]
Hello!
I installed the plugin following the tutorial and also made the changes in the atto editor toolbar config.
The problem I'm facing is that the plugin still doesn't show up in the editor.
I tried different browsers and checked for errors in the installation process and couldn't find anything wrong.
Maybe someone has experienced something similar?

**Comment by nenorojas** [comment]
Hi @mirstigais , could you please let us know the version of Moodle and theme that you are using? If it's not one of the Moodle core themes, I'd ask you first to check if changing to one of the core themes and see if the icon appears. Regards
