### ISSUE TITLE
Transcript not saving with the video

### ISSUE THREAD

**Issue by sharpchi** [enovation/moodle-atto_teamsmeeting#41]
When you record a teams meeting from atto link, the video is saved to the link creator's onedrive "recordings" folder. If transcription is on, when the call has ended, the chat indicates that the transcription has been saved, but it's inaccessible.

![Screenshot 2021-09-22 at 16 04 39 (1)](https://user-images.githubusercontent.com/3774280/134684108-48701e6b-4701-46a8-9da5-78cde7205005.png)

Is this something that can be fixed in this plugin, or there something else that needs to be set for the transcripts to be saved. Note: Transcripts _are_ saved when created through regular calendar team events.

**Comment by nenorojas** [comment]
Hi @sharpchi , 

That's not related to the plugin, you will need to raise the issue with Microsoft Teams support. 

Regards
