### ISSUE TITLE
Moodle Closed the connection

### ISSUE THREAD

**Issue by proghady** [enovation/moodle-atto_teamsmeeting#44]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/8488967/159654380-c09d0e1d-ac38-47d0-a6f8-19243bc92148.png)
I am geeting this error when trying to create a meeting, although I can create it directly from https://enovation.ie/msteams

**Comment by lalitm14** [comment]
hi, I am getting same error please advise how to resolve this error ?

**Comment by nenorojas** [comment]
Hi @proghady , @lalitm14 ,

Please check your server configuration if eventually is not the same issue reported here: https://github.com/enovation/moodle-atto_teamsmeeting/issues/43.

Depending where your Moodle is hosted, that might need to be adjusted.

Please let us know the results.

Regards

**Comment by nenorojas** [comment]
Closing as the server changes mentioned on issue https://github.com/enovation/moodle-atto_teamsmeeting/issues/43 fixed the issue.
