### ISSUE TITLE
Tinymce version

### ISSUE THREAD

**Issue by kkiiskin** [enovation/moodle-atto_teamsmeeting#47]
Hi 

are you planning a tinymce version of this plugin?

**Comment by weilai-irl** [comment]
Hi @kkiiskin 

Short answer to the question is no.

Even the atto editor of the plugin will be made deprecated soon as Microsoft suggests using the Teams LTI feature for meetings. See https://learn.microsoft.com/en-us/microsoft-365/lti/teams-classes-meetings-with-moodle?view=o365-worldwide.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @kkiiskin,

FYI, apparently my comments in the last note is incorrect - we are actually working on a Tiny editor plugin with the same functionality of the Atto editor. It should be published in the coming weeks.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @kkiiskin 

I'm happy to announce that the TinyMCE version has been released at https://moodle.org/plugins/tiny_teamsmeeting. Please download and try it out.

I'm going to close this request.

Regards,
Lai
