### ISSUE TITLE
Default Meetings app URL not working

### ISSUE THREAD

**Issue by sollericos** [enovation/moodle-atto_teamsmeeting#48]
Hi,

Until last Friday it was working rigth, but now we're unable to create a teams meeting if we configured the default URL.

We have configured the old and deprecated URL (https://enovation.ie/msteams) and everything is working again.
Moodle 3.11 & 4.1.6, plugin version 1.2.5

Ciao.

**Comment by weilai-irl** [comment]
Hi @sollericos 

I acknowledge the issue. The teams meetings app at the new default location seems to be broken. I'll try to fix it and provide updates.

Regards,
Lai

**Comment by weilai-irl** [comment]
Hi @sollericos 

The teams meetings app at the new default location is back working now.
Thank you for reporting the issue. I'll mark it closed now.

Regards,
Lai

**Comment by sollericos** [comment]
Hi @weilai-irl 
Still not working, maybe it's an issue with my browser (redirect matters, I presume).
I've changed the URL to https://enomsteams.z16.web.core.windows.net/#/signin and it's working fine for me.
