### ISSUE TITLE
Invalid language tag (locale) with custom Moodle language pack

### ISSUE THREAD

**Issue by microxoft** [enovation/moodle-atto_teamsmeeting#6]
I've installed this plugin on a Moodle 3.8 server, and the popup window shows blank. It won't show the option of login or anything else at all.

This problem is related to https://enovation.ie/msteams/static/node_modules/react-intl/lib/components/provider.js file, and happens with custom moodle language packs that have underscore "_". Please check this similar issue on another plugin: https://github.com/blindsidenetworks/moodle-mod_recordingsbn/issues/16

**Comment by microxoft** [comment]
Still same error message. My language is "es_mx". If I manually assign a parent language it works:

$params = [
        'clientdomain' => encode_url($CFG->wwwroot),
        'appurl' => get_config('atto_teamsmeeting', 'meetingapplink'),
        'locale' => 'es' //empty($parent_lang) ? $lang : $parent_lang
    ];

**Comment by sampraxis** [comment]
I have the same problem with danish "da_rum", but it seem that get_parent_language(...) function doesn't get the parent language for some language. Perhaps your language pack does not have parent language.

Here I think I found some discussion on your language https://moodle.org/mod/forum/discuss.php?d=334067

**Comment by avegys** [comment]
Hi Sam and Miguel,

The issue here is actually not on the Moodle side. We have updated Teams Meetings App https://enovation.ie/msteams today and the app should load with any locale now.
If you are hosting your own MS Teams Meetings application (not https://enovation.ie/msteams), please update it from github.

Best regards,
Andrius

**Comment by microxoft** [comment]
Hello, Avegys.

Thanks a lot for this piece of information!

I’ll check it out and give the proper feedback.

**Comment by sampraxis** [comment]
You are right that MS Teams Meeting is response with error.
If there is a fix from Microsoft it will certainly solve the issue without fix the plugin.
