### ISSUE TITLE
Requesting version for Moodle 3.1

### ISSUE THREAD

**Issue by sagherd** [enovation/moodle-atto_teamsmeeting#7]
Dear Developer
This plugin would be very useful for our teachers during the Covid-19 lock down period and beyond. May i humbly request a version for Moodle 3.1

**Comment by avegys** [comment]
Hi @sagherd,

We have released a new version of the plugin which works now with Moodle 3.1 too.

Bets regards,
Andrius

**Comment by sagherd** [comment]
Excellent. Thank you.
